// src/lib/features/EditProfileModal.svelte
<script lang="ts">
	import { IconPencil, IconSpinner } from '$lib/components/icons';
	import { Modal, Button, UserAvatar } from '$lib/components';
	import { userStore } from '$lib/stores';
	import { GUEST_USER } from '$lib/constants';

	interface Props {
		onClose: () => void;
	}

	let { onClose }: Props = $props();

	const BIO_MAX_LENGTH = 80;

	let bio = $state('');
	let name = $state('');
	let isSubmitting = $state(false);
	let previewImageUrl = $state<string | null>(null);
	let fileInput = $state<HTMLInputElement>();

	const user = $derived(userStore.current || GUEST_USER);

	function handleImageSelect(e: Event) {
		const target = e.target as HTMLInputElement;
		const selectedFile = target.files?.[0];

		if (selectedFile) {
			const imageUrl = URL.createObjectURL(selectedFile);
			previewImageUrl = imageUrl;
		} else {
			previewImageUrl = null;
		}
	}

	function handleCancelCrop() {
		if (previewImageUrl) {
			URL.revokeObjectURL(previewImageUrl);
		}
		previewImageUrl = null;
		if (fileInput) fileInput.value = '';
	}

	async function handleApply() {
		isSubmitting = true;
		try {
			// TODO: Implement save profile API call
			onClose();
		} catch (error) {
			console.error('Error saving profile:', error);
		} finally {
			isSubmitting = false;
		}
	}
</script>

<Modal isOpen={true} {onClose} onBack={previewImageUrl ? handleCancelCrop : undefined}>
	<div class="p-6">
		{#if !previewImageUrl}
			<!-- Edit Form -->
			<div class="space-y-6">
				<!-- Profile Photo -->
				<div class="flex flex-col items-center border-b pb-6">
					<h3 class="font-semibold text-gray-700 mb-4">Profile photo</h3>
					<label for="profile-photo-input" class="relative cursor-pointer">
						<UserAvatar size={16} {user} />
						<button
							type="button"
							aria-label="Edit profile photo"
							class="absolute bottom-0 right-0 rounded-full bg-white shadow-xl border border-gray-300 w-8 h-8 flex items-center justify-center"
						>
							<IconPencil class="w-4 h-4" />
						</button>
					</label>
					<input
						bind:this={fileInput}
						class="hidden"
						type="file"
						id="profile-photo-input"
						onchange={handleImageSelect}
						accept="image/png, image/jpeg, image/jpg"
					/>
				</div>

				<!-- Name -->
				<div class="border-b pb-6">
					<h3 class="font-semibold text-gray-700 mb-4">Name</h3>
					<input
						type="text"
						bind:value={name}
						placeholder="Name"
						class="w-full p-3 border-2 border-gray-300 rounded-lg outline-none focus:border-purple-500"
					/>
				</div>

				<!-- Bio -->
				<div>
					<h3 class="font-semibold text-gray-700 mb-4">Bio</h3>
					<textarea
						bind:value={bio}
						maxlength={BIO_MAX_LENGTH}
						rows="4"
						class="resize-none w-full p-3 bg-gray-50 text-gray-800 border-2 border-gray-300 rounded-lg outline-none focus:border-purple-500"
					></textarea>
					<p class="text-gray-500 text-sm mt-1">{bio.length}/{BIO_MAX_LENGTH}</p>
				</div>
			</div>
		{:else}
			<!-- Image Preview -->
			<div class="flex flex-col items-center">
				<div class="max-w-md max-h-96 overflow-hidden rounded-lg">
					<img src={previewImageUrl} alt="Preview" class="max-w-full max-h-80" />
				</div>
				<p class="text-center text-gray-600 mt-4">
					Preview your new profile photo
				</p>
			</div>
		{/if}

		<!-- Footer Buttons -->
		<div class="flex justify-end gap-3 mt-6 pt-6 border-t">
			{#if !previewImageUrl}
				<Button variant="outline" disabled={isSubmitting} onclick={onClose}>
					{#snippet children()}
						Cancel
					{/snippet}
				</Button>
				<Button variant="primary" disabled={isSubmitting} onclick={handleApply}>
					{#snippet children()}
						{#if isSubmitting}
							<IconSpinner class="w-5 h-5 animate-spin mr-2" />
							Saving...
						{:else}
							Apply
						{/if}
					{/snippet}
				</Button>
			{:else}
				<Button variant="outline" disabled={isSubmitting} onclick={handleCancelCrop}>
					{#snippet children()}
						Cancel
					{/snippet}
				</Button>
				<Button variant="primary" disabled={isSubmitting} onclick={handleApply}>
					{#snippet children()}
						Apply Photo
					{/snippet}
				</Button>
			{/if}
		</div>
	</div>
</Modal>

// src/components/Modals/EditProfileModal/EditProfileModal.tsx
import { useState, useRef } from 'react';
import { PencilIcon, SpinnerGapIcon, XIcon } from '@phosphor-icons/react';
import ReactCrop, { centerCrop, makeAspectCrop } from 'react-image-crop';
import type { Crop, PixelCrop } from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

import UserAvatar from '~/components/UserAvatar';
import type { UserData } from '~/types';
import Button from '~/components/Buttons/Button';
import TextInput from '~/components/TextInput';

interface EditProfileModalProps {
    onClose: () => void;
}

const BIO_MAX_LENGTH = 80;
const DEFAULT_CROP_WIDTH = 50;

function EditProfileModal({ onClose }: EditProfileModalProps) {
    const [bio, setBio] = useState('');
    const [name, setName] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [previewImageUrl, setPreviewImageUrl] = useState<string | null>(null);
    const [cropConfig, setCropConfig] = useState<Crop>();
    const [completedCropConfig, setCompletedCropConfig] = useState<PixelCrop>();
    const imageRef = useRef<HTMLImageElement>(null);

    const handleImageSelect = (event: any) => {
        const selectedFile = event.currentTarget.files?.[0];

        if (selectedFile) {
            const imageUrl = URL.createObjectURL(selectedFile);
            setPreviewImageUrl(imageUrl);
        } else {
            setPreviewImageUrl(null);
            setCropConfig(undefined);
        }
    };

    const handleImageLoad = (event: { currentTarget: HTMLImageElement }) => {
        const { width, height } = event.currentTarget;
        const centeredCrop = centerCrop(
            makeAspectCrop(
                {
                    unit: '%',
                    width: DEFAULT_CROP_WIDTH,
                },
                1,
                width,
                height,
            ),
            width,
            height,
        );
        setCropConfig(centeredCrop);
    };

    const handleCancelCrop = () => {
        if (previewImageUrl) {
            URL.revokeObjectURL(previewImageUrl);
        }
        setPreviewImageUrl(null);
        setCropConfig(undefined);
    };

    const handleApplyCrop = async () => {
        if (!previewImageUrl || !completedCropConfig || !imageRef.current) return;

        setIsSubmitting(true);
        try {
            console.log('Applying crop:', completedCropConfig);
            handleCancelCrop();
        } catch (error) {
            console.error('Error cropping image:', error);
        } finally {
            setIsSubmitting(false);
        }
    };

    const guestUser: UserData = {
        id: 1,
        nickname: 'test',
        avatar: 'test',
    };

    return (
        <div className="fixed flex justify-center pt-14 md:pt-[70px] z-50 top-0 left-0 w-full h-full bg-black/50 overflow-auto">
            <div className="relative bg-white w-full max-w-[700px] p-12 rounded-lg mb-10">
                {/* Header */}
                <div className="absolute flex items-center justify-between w-full p-5 left-0 top-0 border-b border-b-gray-300">
                    <h1 className="text-[22px] font-medium">
                        {previewImageUrl ? 'Crop Profile Photo' : 'Edit Profile'}
                    </h1>
                    <button
                        onClick={previewImageUrl ? handleCancelCrop : onClose}
                        disabled={isSubmitting}
                        className="hover:bg-gray-200 p-1 rounded-full"
                    >
                        <XIcon size={25} />
                    </button>
                </div>

                {/* Main Content */}
                <div className="mt-16">
                    {!previewImageUrl ? (
                        // Edit Form
                        <div className="space-y-6">
                            {/* Profile Photo */}
                            <div className="flex flex-col border-b pb-6">
                                <h3 className="font-semibold text-[15px] text-gray-700 mb-4">
                                    Profile photo
                                </h3>
                                <div className="flex justify-center">
                                    <label
                                        htmlFor="profile-photo-input"
                                        className="relative cursor-pointer"
                                    >
                                        <UserAvatar size={28} user={guestUser} />
                                        <button
                                            type="button"
                                            className="absolute bottom-0 right-0 rounded-full bg-white shadow-xl border p-1 border-gray-300 w-8 h-8"
                                        >
                                            <PencilIcon className="mx-auto" size={17} />
                                        </button>
                                    </label>
                                    <input
                                        className="hidden"
                                        type="file"
                                        id="profile-photo-input"
                                        onChange={handleImageSelect}
                                        accept="image/png, image/jpeg, image/jpg"
                                    />
                                </div>
                            </div>

                            {/* Name */}
                            <div className="flex flex-col border-b pb-6">
                                <h3 className="font-semibold text-[15px] text-gray-700 mb-4">
                                    Name
                                </h3>
                                <div className="flex justify-center">
                                    <div className="w-full max-w-md">
                                        <TextInput
                                            string={name}
                                            placeholder="Name"
                                            onUpdate={setName}
                                            inputType="text"
                                            error=""
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* Bio */}
                            <div className="flex flex-col">
                                <h3 className="font-semibold text-[15px] text-gray-700 mb-4">
                                    Bio
                                </h3>
                                <div className="flex justify-center">
                                    <div className="w-full max-w-md">
                                        <textarea
                                            cols={30}
                                            rows={4}
                                            value={bio}
                                            onChange={(e) =>
                                                setBio(e.currentTarget.value)
                                            }
                                            maxLength={BIO_MAX_LENGTH}
                                            className="resize-none w-full bg-[#F1F1F2] text-gray-800 border border-gray-300 rounded-md py-2.5 px-3 focus:outline-none"
                                        />
                                        <p className="text-[11px] text-gray-500 mt-1">
                                            {bio.length}/{BIO_MAX_LENGTH}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ) : (
                        // Image Cropper
                        <div className="flex flex-col items-center">
                            <div className="max-w-md max-h-96 overflow-hidden">
                                <ReactCrop
                                    crop={cropConfig}
                                    onChange={(_, percentCrop) =>
                                        setCropConfig(percentCrop)
                                    }
                                    onComplete={setCompletedCropConfig}
                                    keepSelection
                                >
                                    <img
                                        ref={imageRef}
                                        src={previewImageUrl}
                                        onLoad={handleImageLoad}
                                        alt="Crop preview"
                                        className="max-w-full max-h-80"
                                    />
                                </ReactCrop>
                            </div>
                            <div className="text-center mt-4 text-gray-600 text-sm">
                                🔹 Kéo các điểm để thay đổi kích thước vùng chọn
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer Buttons */}
                <div className="absolute p-5 left-0 bottom-0 border-t border-t-gray-300 w-full">
                    {!previewImageUrl ? (
                        <div className="flex justify-end gap-3">
                            <Button
                                variant="outline"
                                disabled={isSubmitting}
                                onClick={onClose}
                            >
                                Cancel
                            </Button>
                            <Button variant="primary" disabled={isSubmitting}>
                                Apply
                            </Button>
                        </div>
                    ) : (
                        <div className="flex justify-end gap-3">
                            <button
                                onClick={handleCancelCrop}
                                disabled={isSubmitting}
                                className="px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleApplyCrop}
                                disabled={isSubmitting}
                                className="px-4 py-2 bg-[#F02C56] text-white rounded-md disabled:opacity-50 flex items-center gap-2"
                            >
                                {isSubmitting ? (
                                    <>
                                        <SpinnerGapIcon
                                            className="animate-spin"
                                            size={20}
                                        />
                                        Processing...
                                    </>
                                ) : (
                                    'Apply Crop'
                                )}
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

export default EditProfileModal;
