// src/lib/components/ActionButton.svelte
<script lang="ts">
	import { IconSpinner } from '~/lib/components/icons';
	import classNames from 'classnames';

	interface Props {
		count?: number;
		onclick?: () => void;
		disabled?: boolean;
		isActive?: boolean;
		isLoading?: boolean;
		children: any;
	}

	let {
		count = 0,
		onclick,
		disabled = false,
		isActive = false,
		isLoading = false,
		children
	}: Props = $props();
</script>

<button
	{onclick}
	{disabled}
	class={classNames(
		'flex flex-col items-center gap-4 p-4 bg-transparent',
		disabled ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'
	)}
>
	<div
		class={classNames(
			'grid place-items-center w-16 h-16 rounded-full',
			isActive ? 'bg-red-100' : 'bg-gray-200'
		)}
	>
		{#if isLoading}
			<IconSpinner class="w-5 h-5 animate-spin" />
		{:else}
			{@render children()}
		{/if}
	</div>
	<span class="text-base font-normal">{count}</span>
</button>

// src/shared/components/Buttons/ActionButton/ActionButton.tsx
import { SpinnerGapIcon } from '@phosphor-icons/react';
import type { ActionButtonProps } from '~/shared/types';
import { BaseButton } from '~/shared/components/Buttons/BaseButton';
import classNames from 'classnames';

export function ActionButton({
    icon,
    count = 0,
    onClick,
    disabled = false,
    isActive = false,
    isLoading = false,
}: ActionButtonProps) {
    return (
        <BaseButton
            onClick={onClick}
            disabled={disabled}
            className={classNames(
                'flex flex-col items-center gap-4 p-4 bg-transparent',
                disabled ? 'cursor-not-allowed opacity-50' : 'cursor-pointer',
            )}
        >
            <div
                className={classNames(
                    'grid place-items-center w-16 h-16 rounded-full',
                    isActive ? 'bg-red-100' : 'bg-gray-200',
                )}
            >
                {isLoading ? <SpinnerGapIcon size={20} /> : icon}
            </div>
            <span className="text-base font-normal">{count}</span>
        </BaseButton>
    );
}
