// src/lib/layouts/TopRightActionBar.svelte
<script lang="ts">
	import { userStore } from '~/lib/stores/userStore';
	import Button from '~/lib/components/Button.svelte';
	import UserAvatar from '~/lib/components/UserAvatar.svelte';
	import Menu from '~/lib/components/Menu.svelte';
	import AuthModal from '~/lib/features/AuthModal.svelte';
	import Tooltip from '~/lib/components/Tooltip.svelte';
	import { IconUpload, IconMessage, IconInbox, IconPlus, IconDots } from '~/lib/components/icons';

	let showAuthModal = $state(false);
	const user = $derived($userStore);
	const isLoggedIn = $derived(user !== null);

	const MENU_ITEMS = [
		{
			icon: '🌐',
			title: 'English',
			children: {
				title: 'Language',
				data: [
					{ icon: '🇺🇸', title: 'English' },
					{ icon: '🇻🇳', title: 'Tiếng Việt' }
				]
			}
		},
		{ icon: '💬', title: 'Feedback and help', to: '/feedback' },
		{ icon: '⌨️', title: 'Keyboard shortcuts' }
	];

	function handleLogout() {
		userStore.set(null);
	}

	function openAuthModal() {
		showAuthModal = true;
	}

	const userMenu = $derived(
		isLoggedIn
			? [
					{
						icon: '👤',
						title: 'View profile',
						to: `/@${user?.nickname || 'test'}`
					},
					{ icon: '💰', title: 'Get coins', to: '/coin' },
					{ icon: '⚙️', title: 'Settings', to: '/settings' },
					...MENU_ITEMS,
					{
						icon: '🚪',
						title: 'Log out',
						separate: true,
						onClick: handleLogout
					}
				]
			: MENU_ITEMS
	);
</script>

<nav class="flex items-center gap-2">
	{#if isLoggedIn}
		<Tooltip content="Upload video">
			<a href="/upload" aria-label="Upload video" class="p-2 hover:bg-gray-100 rounded-full">
				<IconUpload class="w-6 h-6" />
			</a>
		</Tooltip>
		<Tooltip content="Messages">
			<button aria-label="Messages" class="p-2 hover:bg-gray-100 rounded-full">
				<IconMessage class="w-6 h-6" />
			</button>
		</Tooltip>
		<Tooltip content="Inbox">
			<button aria-label="Inbox" class="p-2 hover:bg-gray-100 rounded-full relative">
				<IconInbox class="w-6 h-6" />
				<span
					class="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center"
				>
					12
				</span>
			</button>
		</Tooltip>
	{:else}
		<Button variant="outline" onclick={openAuthModal}>
			{#snippet children()}
				<IconPlus class="w-5 h-5 mr-2" />
				Upload
			{/snippet}
		</Button>
		<Button variant="primary" onclick={openAuthModal}>
			{#snippet children()}
				Log in
			{/snippet}
		</Button>
	{/if}

	<Menu items={userMenu} hover={true}>
		<div class="ml-2">
			{#if isLoggedIn}
				<UserAvatar size={10} {user} />
			{:else}
				<div class="p-2 hover:bg-gray-100 rounded-full">
					<IconDots class="w-6 h-6" />
				</div>
			{/if}
		</div>
	</Menu>
</nav>

<AuthModal isOpen={showAuthModal} onClose={() => (showAuthModal = false)} />

// src/Layouts/components/Header/TopRightActionBar.tsx
import { useState } from 'preact/hooks';

import {
    PlusIcon,
    DotsThreeVerticalIcon,
    ArrowUpIcon,
    ChatIcon,
    EnvelopeIcon,
} from '@phosphor-icons/react';

import config from '~/core/config';
import { Menu, Button, LinkButton } from '~/shared';
import type { MenuItemData } from '~/shared/types';
import { useCurrentUser } from '~/shared/hooks';
import { AuthModal } from '~/features/Modals';
import { UserAvatar } from '~/features';

const MENU_ITEMS: MenuItemData[] = [
    {
        icon: '',
        title: 'English',
        children: {
            title: 'Language',
            data: [
                { type: 'language', code: 'en', title: 'English' },
                { type: 'language', code: 'vi', title: 'Tiếng Việt' },
            ],
        },
    },
    { icon: '', title: 'Feedback and help', to: '/feedback' },
    { icon: '', title: 'Keyboard shortcuts' },
];

function TopRightActionBar() {
    const { user, setUser } = useCurrentUser();
    const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
    const isLoggedIn = user !== null;

    const handleLogout = () => setUser(null);
    const openAuthModal = () => setIsAuthModalOpen(true);
    const closeAuthModal = () => setIsAuthModalOpen(false);

    const userMenu: MenuItemData[] = [
        {
            icon: '',
            title: 'View profile',
            to: `/@${user?.nickname || 'test'}`,
        },
        { icon: '', title: 'Get coins', to: '/coin' },
        { icon: '', title: 'Settings', to: '/settings' },
        ...MENU_ITEMS,
        {
            icon: '',
            title: 'Log out',
            to: '#',
            separate: true,
            onClick: handleLogout,
        },
    ];

    const renderLoggedInActions = () => (
        <>
            <LinkButton
                to={config.routes.upload}
                icon={<ArrowUpIcon size={25} />}
                tooltip="Upload video"
            />
            <LinkButton icon={<ChatIcon size={25} />} tooltip="Messages" />
            <LinkButton icon={<EnvelopeIcon size={25} />} tooltip="Inbox" badge={12} />
        </>
    );

    const renderGuestActions = () => (
        <div className="flex space-x-3">
            <Button variant="outline" onClick={openAuthModal} leftIcon={<PlusIcon />}>
                Upload
            </Button>
            <Button variant="primary" onClick={openAuthModal}>
                Log in
            </Button>
        </div>
    );

    const renderAvatar = () => (
        <div className="ml-3">
            {isLoggedIn ? (
                <UserAvatar
                    size={10}
                    user={user}
                    fallback="https://yt3.ggpht.com/Pa8wyxqTOkhu5DW_RvkiQIS7Bsa7OW7gSen-2WpaQsC2EqUAkgubAg1_QPc951pzpN2F2Q4_TA=s88-c-k-c0x00ffffff-no-rj"
                />
            ) : (
                <button className="flex ml-1 rounded-full cursor-pointer">
                    <DotsThreeVerticalIcon size={25} weight="bold" />
                </button>
            )}
        </div>
    );

    return (
        <>
            <AuthModal isOpen={isAuthModalOpen} onClose={closeAuthModal} />
            <nav className="flex items-center">
                {isLoggedIn ? renderLoggedInActions() : renderGuestActions()}

                <Menu
                    items={isLoggedIn ? userMenu : MENU_ITEMS}
                    onChange={(item) => item.title === 'Log out' && handleLogout()}
                >
                    {renderAvatar()}
                </Menu>
            </nav>
        </>
    );
}

export default TopRightActionBar;
