// src/Layouts/components/LoadingOverlay/LoadingOverlay.tsx
import { SpinnerIcon } from '@phosphor-icons/react';

export function LoadingOverlay() {
    return (
        <div
            className="fixed top-24 left-1/2 -translate-x-1/2 
                       bg-gradient-to-r from-purple-600 to-pink-600 
                       text-white px-8 py-4 rounded-full z-[60]
                       text-base font-normal shadow-2xl backdrop-blur-sm
                       flex items-center gap-4"
        >
            <SpinnerIcon className="w-5 h-5" />
            <span>Đang tải video mới...</span>
        </div>
    );
}

// src/lib/layouts/components/LoadingOverlay.svelte
<div
	class="fixed top-24 left-1/2 -translate-x-1/2 
		bg-gradient-to-r from-purple-600 to-pink-600 
		text-white px-8 py-4 rounded-full z-[60]
		text-base font-normal shadow-2xl backdrop-blur-sm
		flex items-center gap-4"
>
	<svg class="w-5 h-5 animate-spin" viewBox="0 0 256 256" fill="currentColor">
		<path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm64-88a8,8,0,0,1-8,8H128a8,8,0,0,1-8-8V72a8,8,0,0,1,16,0v48h48A8,8,0,0,1,192,128Z"/>
	</svg>
	<span>Đang tải video mới...</span>
</div>
