// src/Layouts/components/Sidebar/Sidebar.tsx
import { useRef, useState, useEffect } from 'preact/hooks';

import Menu from './Menu/Menu';
import MenuItem from './Menu/MenuItem';
import { SuggestedAccounts } from '~/features';
import * as userServices from '~/core/services/userService';
import { SIDEBAR_MENU } from './SidebarMenu';
import { Search } from '~/Layouts/components';

const INIT_PAGE = 1;
const PER_PAGE = 5;

function Sidebar() {
    const [page, setPage] = useState(INIT_PAGE);
    const [suggestedUsers, setSuggestedUsers] = useState<any[]>([]);

    const fetchedRef = useRef(false);
    useEffect(() => {
        if (fetchedRef.current && page === INIT_PAGE) return;
        fetchedRef.current = true;

        userServices
            .getSuggested({ page: page, perPage: PER_PAGE })
            .then((data) => {
                setSuggestedUsers((prev) =>
                    page === INIT_PAGE ? data : [...prev, ...data],
                );
            })
            .catch(console.error);
    }, [page]);

    const handleSeeAll = () => {
        setPage((prev) => prev + 1);
    };

    return (
        <aside id="Sidebar" className="fixed top-[70px] bottom-0 w-[280px] px-2.5 z-40">
            <Menu>
                <Search />
                <nav className="my-[12px]">
                    {SIDEBAR_MENU.map((item) => (
                        <MenuItem key={item.title} {...item} />
                    ))}
                </nav>
            </Menu>
            <section>
                <SuggestedAccounts
                    label="Suggested accounts"
                    data={suggestedUsers}
                    onSeeAll={handleSeeAll}
                />
            </section>
            <section>
                <SuggestedAccounts label="Following" />
            </section>
            <footer className="py-4 w-full">
                <hr className="border-gray-400 w-[90%]"></hr>
                <section className="text-base font-normal text-gray-700 w-full">
                    <p>Following accounts</p>
                    <p>Accounts you follow will appear here</p>
                </section>
                <hr className="border-gray-400 w-[90%]"></hr>

                <ul className="text-base font-normal text-gray-500 w-full space-y-1">
                    <li>Company</li>
                    <li>Program</li>
                    <li>Terms & Policies</li>
                    <li>© 2025 TikTok</li>
                </ul>
            </footer>
        </aside>
    );
}

export default Sidebar;

// src/lib/layouts/components/Sidebar.svelte
<script lang="ts">
	import MenuItem from './MenuItem.svelte';
	import Search from './Search.svelte';
	import SuggestedAccounts from '~/lib/features/SuggestedAccounts.svelte';
	import * as userServices from '~/core/services/userService';

	const INIT_PAGE = 1;
	const PER_PAGE = 5;

	let currentPage = $state(INIT_PAGE);
	let suggestedUsers = $state<any[]>([]);
	let fetchedRef = false;

	const SIDEBAR_MENU = [
		{
			title: 'For You',
			to: '/',
			icon: 'house',
		},
		{
			title: 'Following',
			to: '/following',
			icon: 'users',
		},
		{
			title: 'LIVE',
			to: '/live',
			icon: 'video',
		},
	];

	// Load when page changes (like useEffect with [page])
	$effect(() => {
		if (fetchedRef && currentPage === INIT_PAGE) return;
		fetchedRef = true;

		userServices
			.getSuggested({ page: currentPage, perPage: PER_PAGE })
			.then((data) => {
				suggestedUsers = currentPage === INIT_PAGE ? data : [...suggestedUsers, ...data];
			})
			.catch(console.error);
	});

	function handleSeeAll() {
		currentPage++;
	}
</script>

<aside id="Sidebar" class="fixed top-[70px] bottom-0 w-[280px] px-2.5 z-40">
	<nav>
		<Search />
		<nav class="my-[12px]">
			{#each SIDEBAR_MENU as item (item.title)}
				<MenuItem {...item} />
			{/each}
		</nav>
	</nav>

	<section>
		<SuggestedAccounts
			label="Suggested accounts"
			data={suggestedUsers}
			onSeeAll={handleSeeAll}
		/>
	</section>

	<section>
		<SuggestedAccounts label="Following" data={[]} />
	</section>

	<footer class="py-4 w-full">
		<hr class="border-gray-400 w-[90%]" />
		<section class="text-base font-normal text-gray-700 w-full">
			<p>Following accounts</p>
			<p>Accounts you follow will appear here</p>
		</section>
		<hr class="border-gray-400 w-[90%]" />

		<ul class="text-base font-normal text-gray-500 w-full space-y-1">
			<li>Company</li>
			<li>Program</li>
			<li>Terms & Policies</li>
			<li>© 2025 TikTok</li>
		</ul>
	</footer>
</aside>
