// src/lib/components/Image.svelte
<script lang="ts">
	import classNames from 'classnames';
	import images from '~/lib/assets/images';

	interface Props {
		src: string;
		alt?: string;
		class?: string;
		rounded?: boolean;
		fallback?: string;
		style?: string;
	}

	let {
		src,
		alt = '',
		class: className = '',
		rounded = false,
		fallback: customFallback = images.noImage,
		style = '',
		...props
	}: Props = $props();

	let fallback = $state('');

	function handleError() {
		fallback = customFallback;
	}
</script>

<img
	class={classNames(
		'overflow-hidden select-none pointer-events-none',
		rounded && 'rounded-full object-cover',
		className
	)}
	src={fallback || src}
	{alt}
	{style}
	onerror={handleError}
	{...props}
/>

// src/components/Image/index.tsx
import classNames from 'classnames/bind';
import { useState } from 'react';
import images from '~/assets/images';
import styles from './Image.module.scss';

const cx = classNames.bind(styles);

function Image({
    src,
    alt,
    className,
    fallback: customFallback = images.noImage,
    ...props
}: any) {
    const [fallback, setFallback] = useState('');

    const handleError = () => {
        setFallback(customFallback);
    };

    return (
        <img
            className={cx(styles.wrapper, className)}
            src={fallback || src}
            alt={alt}
            {...props}
            onError={handleError}
        />
    );
}

export default Image;
