// src/shared/components/Tooltip/Tooltip.tsx
import { useEffect, useRef, useState } from 'preact/hooks';
import classNames from 'classnames';

import {
    useFloating,
    offset,
    shift,
    arrow,
    useHover,
    useInteractions,
    FloatingPortal,
    useTransitionStyles,
    type Placement,
} from '@floating-ui/react';
import Arrow from './Arrow';
import './Tooltip.css';

interface TooltipProps {
    children: React.ReactNode;
    visible?: boolean;
    onVisibleChange?: (visible: boolean) => void;
    content?: React.ReactNode;
    render?: () => React.ReactNode;
    delay?: number | [number, number];
    offset?: number | [number, number];
    placement?: Placement;
    onClickOutside?: () => void;
    animation?: boolean;
    animationDuration?: number;
    className?: string;
}

export function Tooltip({
    children,
    visible,
    onVisibleChange,
    content,
    render,
    delay = 0,
    offset: offsetValue = 6,
    placement = 'bottom',
    onClickOutside,
    animation = true,
    animationDuration = 200,
    className,
}: TooltipProps) {
    const [isOpen, setIsOpen] = useState(false);
    const arrowRef = useRef<HTMLDivElement>(null);
    const wrapperRef = useRef<HTMLDivElement>(null);

    const showTooltip = visible ?? isOpen;

    const handleOpenChange = (open: boolean) => {
        if (visible !== undefined) {
            onVisibleChange?.(open);
        } else {
            setIsOpen(open);
        }
    };

    const offsetMiddleware = Array.isArray(offsetValue)
        ? offset({ mainAxis: offsetValue[1], crossAxis: offsetValue[0] })
        : offset(offsetValue);

    const middleware = [offsetMiddleware, shift()];
    if (content) {
        middleware.push(arrow({ element: arrowRef }));
    }

    const { x, y, refs, context, middlewareData } = useFloating({
        open: showTooltip,
        onOpenChange: handleOpenChange,
        placement,
        middleware,
    });

    const hoverDelay = Array.isArray(delay) ? { open: delay[0], close: delay[1] } : delay;

    const { getReferenceProps, getFloatingProps } = useInteractions([
        useHover(context, { delay: hoverDelay }),
    ]);

    const { isMounted, styles: transitionStyles } = useTransitionStyles(context, {
        duration: 0,
        initial: { opacity: 1, transform: 'scale(1)' },
        open: { opacity: 1, transform: 'scale(1)' },
        close: { opacity: 1, transform: 'scale(1)' },
    });

    useEffect(() => {
        if (wrapperRef.current) {
            const firstChild = wrapperRef.current.firstElementChild;
            if (firstChild) {
                refs.setReference(firstChild as HTMLElement);
            }
        }
    }, [children, refs]);

    useEffect(() => {
        if (!showTooltip || !onClickOutside) return;

        const handleClickOutside = (e: MouseEvent) => {
            const target = e.target as Node;
            const isClickInside =
                refs.floating.current?.contains(target) ||
                wrapperRef.current?.contains(target);

            if (!isClickInside) {
                onClickOutside();
            }
        };

        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [showTooltip, onClickOutside, refs.floating]);

    const { x: arrowX, y: arrowY } = middlewareData.arrow || {};

    return (
        <>
            <div
                ref={wrapperRef}
                className={classNames(className, 'wrapper')}
                {...getReferenceProps()}
            >
                {children}
            </div>
            {isMounted && (
                <FloatingPortal>
                    <div
                        ref={refs.setFloating}
                        style={{
                            position: 'absolute',
                            top: y ?? 0,
                            left: x ?? 0,
                            zIndex: 9999,
                            visibility: showTooltip ? 'visible' : 'hidden',
                            ...transitionStyles,
                        }}
                        className={
                            content
                                ? 'text-white font-normal bg-black px-2 py-1 rounded text-base select-none'
                                : ''
                        }
                        {...getFloatingProps()}
                    >
                        {content || render?.()}
                        {content && (
                            <Arrow
                                arrowRef={arrowRef}
                                placement={placement}
                                arrowX={arrowX}
                                arrowY={arrowY}
                                hasContent={true}
                            />
                        )}
                    </div>
                </FloatingPortal>
            )}
        </>
    );
}

// src/lib/components/Tooltip.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { Snippet } from 'svelte';

	interface Props {
		content?: string;
		render?: Snippet;
		children: Snippet;
		placement?: 'top' | 'bottom' | 'left' | 'right' | 'bottom-start' | 'bottom-end';
		delay?: number;
		offset?: [number, number];
		visible?: boolean;
		onClickOutside?: () => void;
	}

	let {
		content,
		render,
		children,
		placement = 'bottom',
		delay = 0,
		offset = [0, 6],
		visible,
		onClickOutside
	}: Props = $props();

	let showTooltip = $state(false);
	let tooltipEl = $state<HTMLDivElement>();
	let wrapperEl = $state<HTMLDivElement>();
	let hoverTimeout: ReturnType<typeof setTimeout>;

	const isVisible = $derived(visible !== undefined ? visible : showTooltip);

	function handleMouseEnter() {
		if (visible === undefined) {
			clearTimeout(hoverTimeout);
			hoverTimeout = setTimeout(() => {
				showTooltip = true;
			}, delay);
		}
	}

	function handleMouseLeave() {
		if (visible === undefined) {
			clearTimeout(hoverTimeout);
			showTooltip = false;
		}
	}

	function handleClickOutside(e: MouseEvent) {
		if (onClickOutside && isVisible) {
			const target = e.target as Node;
			const isClickInside =
				tooltipEl?.contains(target) || wrapperEl?.contains(target);

			if (!isClickInside) {
				onClickOutside();
			}
		}
	}

	onMount(() => {
		if (onClickOutside) {
			document.addEventListener('mousedown', handleClickOutside);
			return () => document.removeEventListener('mousedown', handleClickOutside);
		}
	});

	// Calculate position
	$effect(() => {
		if (isVisible && tooltipEl && wrapperEl) {
			const rect = wrapperEl.getBoundingClientRect();
			const [crossAxis, mainAxis] = offset;
			const tooltipWidth = tooltipEl.offsetWidth;
			const tooltipHeight = tooltipEl.offsetHeight;
			const viewportWidth = window.innerWidth;
			const viewportHeight = window.innerHeight;

			let top = 0;
			let left = 0;

			if (placement === 'bottom' || placement === 'bottom-start' || placement === 'bottom-end') {
				top = rect.bottom + mainAxis;
				if (placement === 'bottom-start') {
					left = rect.left + crossAxis;
				} else if (placement === 'bottom-end') {
					left = rect.right - tooltipWidth + crossAxis;
				} else {
					left = rect.left + rect.width / 2 - tooltipWidth / 2 + crossAxis;
				}
			} else if (placement === 'top') {
				top = rect.top - tooltipHeight - mainAxis;
				left = rect.left + rect.width / 2 - tooltipWidth / 2 + crossAxis;
			} else if (placement === 'left') {
				top = rect.top + rect.height / 2 - tooltipHeight / 2 + crossAxis;
				left = rect.left - tooltipWidth - mainAxis;
			} else if (placement === 'right') {
				top = rect.top + rect.height / 2 - tooltipHeight / 2 + crossAxis;
				left = rect.right + mainAxis;
			}

			// Keep within viewport bounds
			if (left + tooltipWidth > viewportWidth) {
				left = viewportWidth - tooltipWidth - 10;
			}
			if (left < 10) {
				left = 10;
			}
			if (top + tooltipHeight > viewportHeight) {
				top = viewportHeight - tooltipHeight - 10;
			}
			if (top < 10) {
				top = 10;
			}

			tooltipEl.style.top = `${top}px`;
			tooltipEl.style.left = `${left}px`;
		}
	});
</script>

<div
	bind:this={wrapperEl}
	class="inline-flex"
	onmouseenter={handleMouseEnter}
	onmouseleave={handleMouseLeave}
	role="tooltip"
>
	{@render children()}
</div>

{#if isVisible}
	<div
		bind:this={tooltipEl}
		class="fixed z-[9999] {content
			? 'px-2 py-1 text-base text-white bg-black rounded font-normal select-none pointer-events-none whitespace-nowrap'
			: ''}"
		style="visibility: {isVisible ? 'visible' : 'hidden'}"
	>
		{#if content}
			{content}
		{:else if render}
			{@render render()}
		{/if}
	</div>
{/if}
