// src/lib/features/AccountPreview.svelte
<script lang="ts">
	import UserAvatar from '~/lib/components/UserAvatar.svelte';

	interface Props {
		user: any;
	}

	let { user }: Props = $props();
</script>

<div class="w-full p-4">
	<a href="/@{user.nickname}">
		<header class="flex justify-between items-start">
			<UserAvatar {user} />
			<button
				class="rounded-md py-4 px-6 text-base text-white font-normal bg-[var(--primary)]"
			>
				Follow
			</button>
		</header>
	</a>
	<section class="mt-4 text-[#161823]">
		<p class="text-base">
			<strong>{user.nickname}</strong>
		</p>
		<p class="text-base text-gray-600">
			{user.first_name}
			{user.last_name}
		</p>
		<p class="mt-4.5 text-base">
			<strong class="mr-1">{user.followers_count}</strong>
			<span class="text-gray-500 mr-5">Followers</span>
			<strong class="mr-1">{user.likes_count}</strong>
			<span class="text-gray-500">Likes</span>
		</p>
	</section>
</div>

// src/components/SuggestedAccounts/AccountPreview/AccountPreview.tsx
import classNames from 'classnames/bind';
import styles from './AccountPreview.module.scss';
import Button from '~/components/Buttons/Button';
import type { UserProps } from '~/types';
import UserAvatar from '~/components/User';

const cx = classNames.bind(styles);

function AccountPreview({ user }: UserProps) {
    return (
        <div className={cx('w-full p-8')}>
            <header className={cx('flex justify-between')}>
                <UserAvatar size={18} user={user} />
                <Button variant="primary">Follow</Button>
            </header>
            <section>
                <p className={cx('text-3xl')}>
                    <strong>{user.nickname}</strong>
                </p>
                <p className={cx('text-2xl')}>{user.first_name + ' ' + user.last_name}</p>
                <p className={cx('mt-4 text-3xl')}>
                    <strong className={cx('value')}>{user.followers_count} </strong>
                    <span className={cx('text-gray-500')}>Followers</span>
                    <strong className={cx('value')}>{user.likes_count} </strong>
                    <span className={cx('text-gray-500')}>Likes</span>
                </p>
            </section>
        </div>
    );
}

export default AccountPreview;
